version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airdrop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    ports:
      - "8080:80"
    networks:
      - airdrop_network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=db

  db:
    image: mysql:8.0
    container_name: airdrop_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: airdrop_portal
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: airdrop_user
      MYSQL_PASSWORD: airdrop_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - airdrop_network

  mailhog:
    image: mailhog/mailhog
    container_name: airdrop_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - airdrop_network

networks:
  airdrop_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

